apiVersion: v1
kind: Pod
metadata:
  name: forxel
  labels:
    app: forxel
spec:
  containers:
    - name: frontend-container
      image: danishpeer1/forxel:ui-v1 # Replace with your frontend container image and tag
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
      env:
        - name: REACT_APP_BACKEND_URL
          value: "http://forxel:8080/api/"
    - name: backend-container
      image: danishpeer1/forxel:v1 # Replace with your frontend container image and tag
      ports:
        - containerPort: 8080
  imagePullSecrets:
  - name: regcred   


