apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-dep
  labels:
    app: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-deployment
  template:
    metadata:
      labels:
        app: db-deployment
    spec:
      containers:
      - name: db-deployment
        image: ghcr.io/oracle/nosql:latest-ce
        ports:
        - containerPort: 80
