apiVersion: v1
kind: Service
metadata:
  name: forxel
spec:
  selector:
    app: forxel
  ports:
    - name: frontend
      port: 3000
      targetPort: 3000
    - name: backend
      port: 8080
      targetPort: 8080
  type: NodePort 
